# .github/workflows/ci.yml
name: reLAISS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4          # grab the code
      - uses: actions/setup-python@v4      # single Python version
        with:
          python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run unit tests
        run: |
          pytest -W ignore::DeprecationWarning
