[theme]
primaryColor = "#4299e1"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1f2e"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
port = 7860
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
